name: MarkdownLint

permissions:
  contents: read

# run even on changes without Markdown changes, so that we can
# make it in GitHub a required check for PR's
on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
    branches:
      - main

jobs:
  lint:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Run MarkdownLint
        run: |
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          npm i -g markdownlint-cli
          markdownlint --ignore 'ui/node_modules/' --ignore 'leps/NNNN-template/' '**/*.md'
